### ISSUE TITLE
prioritization metric: car ownership

### ISSUE THREAD

**Issue by michaelkirk** [a-b-street/ltn#155]
Same as density/simd, we'll do an area proportional aggregation.

We are interested in the ratio of households with _at least one car_ - households with 3 cars are counted the same as households with 1 car.

The output of the metric should be `households_with_at_least_one_car / total_households`. 

The English example at https://acteng.github.io/atip/browse.html?style=dataviz&census_output_areas=percent_households_with_car#6.6/54.775/-1.177 shows "percentage of households with a car", which is not quite the format we need in order to aggregate across these zones, but I assume the underlying data we need is there.

Specifically, we'll need to know the **total number of households** in the geometry to have a reasonable aggregation strategy. As an extreme example, if my neighborhood contains exactly two car-ownership-geometries (pretend they are fully included, not clipped)

```
car_ownership_1:
  area: 1.0
  households_with_a_car: 100%
  total_households: 100

car_ownership_2:
  area: 1.0
  households_with_a_car: 0%
  total_households: 900
```

The aggregate households_with_a_car should be ~10% (not  50%).

From that point, applying our usual area-proportional clipping should be straight forward.
